version: '3.8'
services:
  db:
    container_name: pg_container_marius
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: car
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container_Marius
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"